-- Access events: which process, on whose laptop, opened which document.
--
-- Read docs/audit-trail.md before extending this. The short version:
--
-- **This is telemetry, not evidence.** The FUSE client runs on the user's own
-- machine, so every field describing the *process* is a claim made by software
-- they control. `cmdline` and `comm` are forgeable without trying — argv is
-- rewritable in place and comm is a prctl call. What the server knows by itself
-- is the token, the document, and the time, and those three are the part that
-- would stand up to an argument.
--
-- It is still worth having. On a managed fleet it answers "what read this?"
-- during an incident, and it distinguishes an agent sweeping the tree from a
-- person opening one page.

create table wiki.access_event (
  -- Generated by the client so delivery can be at-least-once: the queue may
  -- resend a batch it never saw acknowledged, and the unique constraint turns
  -- the duplicate into a no-op instead of a second row.
  event_id     uuid primary key,

  -- Who, as the server understands it. Not taken from the payload.
  principal_id uuid not null references wiki.principal(id) on delete cascade,
  document_id  uuid references wiki.document(id) on delete set null,
  path         ltree,

  occurred_at  timestamptz not null,
  recorded_at  timestamptz not null default now(),

  -- 'open', and room for whatever else earns a record later.
  action       text not null,
  -- O_RDONLY/O_WRONLY/... as the mount saw them, for telling a read from an
  -- edit without guessing.
  open_flags   integer,

  -- The client's claim about the process. Deliberately one jsonb column rather
  -- than columns per field: the shape is the client's, it will change, and
  -- promoting any of it to a first-class column would suggest the server
  -- believes it.
  process      jsonb,

  -- Reads, and the mutations that carry a caller. Not one per FUSE operation:
  -- write() gets a file handle and no process at all, so a 'write' here is the
  -- rename that lands an editor's temp file on a real path, which is where the
  -- bytes actually become a draft. An in-place save carries no rename and
  -- shows up as an 'open' whose open_flags say O_WRONLY|O_TRUNC.
  constraint access_event_action_known
    check (action in ('open', 'create', 'write', 'delete', 'move')),
  -- A record that predates the wiki, or arrives from the future, is a broken
  -- client clock rather than a fact. Keep it, but keep it recognisable.
  constraint access_event_when check (occurred_at > '2020-01-01'::timestamptz)
);

create index access_event_principal_idx on wiki.access_event (principal_id, occurred_at desc);
create index access_event_document_idx  on wiki.access_event (document_id, occurred_at desc)
  where document_id is not null;

comment on table wiki.access_event is
  'Client-reported document opens. The principal, document and time are the '
  'server''s; everything in `process` is the client''s claim about itself.';

alter table wiki.access_event enable row level security;

-- You may see your own trail, and nothing else. Reading everyone's is an
-- administrative act and belongs to a role that does not serve web requests.
create policy access_event_select_own on wiki.access_event
  for select using (principal_id = wiki.current_user_id());

-- Insert-only, and only about yourself. There is deliberately no update or
-- delete policy: an audit trail its subject can edit is not one. (They can of
-- course decline to send anything at all — see the trust note above.)
create policy access_event_insert_own on wiki.access_event
  for insert with check (principal_id = wiki.current_user_id());

grant select, insert on wiki.access_event to fswiki_user;

------------------------------------------------------------------------------
-- Recording
------------------------------------------------------------------------------

-- Take a batch of events. One round trip for a queue flush, and the caller's
-- identity comes from the token rather than the payload, so a client cannot
-- file events against somebody else.
--
-- Returns how many were new. A client that resends a batch gets 0 and can drop
-- it, which is the whole point of the client-generated event_id.
create or replace function wiki.record_opens(p_events jsonb)
returns integer
language plpgsql volatile
set search_path = wiki, public, pg_temp as $$
declare
  v_user  uuid := wiki.current_user_id();
  v_added integer;
begin
  if v_user is null then
    raise exception 'recording access events requires an authenticated caller'
      using errcode = 'insufficient_privilege';
  end if;
  if jsonb_typeof(p_events) <> 'array' then
    raise exception 'expected an array of events'
      using errcode = 'invalid_parameter_value';
  end if;

  insert into wiki.access_event
    (event_id, principal_id, document_id, path, occurred_at, action,
     open_flags, process)
  select (e ->> 'event_id')::uuid,
         v_user,
         (e ->> 'document_id')::uuid,
         (e ->> 'path')::ltree,
         (e ->> 'occurred_at')::timestamptz,
         coalesce(e ->> 'action', 'open'),
         (e ->> 'open_flags')::integer,
         e -> 'process'
    from jsonb_array_elements(p_events) e
  -- Resends are expected, not exceptional.
  on conflict (event_id) do nothing;

  get diagnostics v_added = row_count;
  return v_added;
end;
$$;

comment on function wiki.record_opens(jsonb) is
  'Record a batch of client-reported opens. Idempotent on event_id, so the '
  'client queue can retry freely. The principal comes from the token, never '
  'from the payload.';

grant execute on function wiki.record_opens(jsonb) to fswiki_user;

------------------------------------------------------------------------------
-- Reading a document, and recording that you did
------------------------------------------------------------------------------

-- The same content a GET on `syncable_document` returns, plus the access
-- event, in one round trip and one transaction.
--
-- The verb is the whole trick. PostgREST runs GET in a **read-only**
-- transaction, which is why recording an access on the read itself looked
-- like it needed an escape hatch — pg_notify, or dblink to a second
-- connection, both of which mean a privileged channel driven by client input
-- (docs/audit-trail.md has the measurements). POST has no such restriction.
-- And it is not a misuse of the verb: a request that records something is not
-- idempotent, which is precisely what POST is for. The read is a side effect
-- of the recording as much as the other way round.
--
-- SECURITY INVOKER, and `syncable_document` is itself a security_invoker view,
-- so this is exactly as filtered as the GET it replaces. It is a second way to
-- read what you could already read, not a second answer about what you may.
--
-- What it changes is who is making the claim. Events off the client queue are
-- the client's word that a read happened; this row is the server's own record
-- of having served the bytes. The `process` field is still the client
-- describing itself and still forgeable — but "this token was handed this
-- document at this time" becomes something the server witnessed.
create or replace function wiki.read_document(
  p_document uuid,
  p_event    jsonb default null
)
returns table (content text)
language plpgsql volatile
set search_path = wiki, public, pg_temp as $$
declare
  v_user    uuid := wiki.current_user_id();
  v_content text;
  v_found   boolean;
begin
  select d.content into v_content
    from wiki.syncable_document d
   where d.id = p_document;
  v_found := found;

  -- Recorded whether or not the read succeeded: a request for something you
  -- cannot have is the more interesting half of an access log. document_id is
  -- only filled in when the row was actually visible, because the foreign key
  -- would otherwise reject a probe for an id that does not exist and take the
  -- read down with it. The path travels in the payload regardless, so a probe
  -- still leaves a mark.
  if v_user is not null and p_event is not null then
    insert into wiki.access_event
      (event_id, principal_id, document_id, path, occurred_at, action,
       open_flags, process)
    values (
      (p_event ->> 'event_id')::uuid,
      v_user,
      case when v_found then p_document end,
      (p_event ->> 'path')::ltree,
      coalesce((p_event ->> 'occurred_at')::timestamptz, now()),
      coalesce(p_event ->> 'action', 'open'),
      (p_event ->> 'open_flags')::integer,
      p_event -> 'process'
    )
    -- The client queues the same event under the same id before it gets here,
    -- so whichever arrives second is a no-op. That is what lets the queue be a
    -- fallback for the cases this cannot see — a refused open, a body served
    -- from a draft, a laptop with no network — without double-counting the
    -- ones it can.
    on conflict (event_id) do nothing;
  end if;

  if v_found then
    return query select v_content;
  end if;
  return;
end;
$$;

comment on function wiki.read_document(uuid, jsonb) is
  'Read one document''s body and record the access in the same transaction. '
  'POST rather than GET because PostgREST runs GET read-only. Identical '
  'visibility to selecting from syncable_document, which it does as invoker.';

grant execute on function wiki.read_document(uuid, jsonb) to fswiki_user;
