

-- Access events: which process, on whose laptop, opened which document.
--
-- Read docs/audit-trail.md before extending this. The short version:
--
-- **This is telemetry, not evidence.** The FUSE client runs on the user's own
-- machine, so every field describing the *process* is a claim made by software
-- they control. `cmdline` and `comm` are forgeable without trying — argv is
-- rewritable in place and comm is a prctl call. What the server knows by itself
-- is the token, the document, and the time, and those three are the part that
-- would stand up to an argument.
--
-- It is still worth having. On a managed fleet it answers "what read this?"
-- during an incident, and it distinguishes an agent sweeping the tree from a
-- person opening one page.

create table wiki.access_event (
  -- Generated by the client so delivery can be at-least-once: the queue may
  -- resend a batch it never saw acknowledged, and the unique constraint turns
  -- the duplicate into a no-op instead of a second row.
  event_id     uuid primary key,

  -- Who, as the server understands it. Not taken from the payload.
  principal_id uuid not null references wiki.principal(id) on delete cascade,
  document_id  uuid references wiki.document(id) on delete set null,
  path         ltree,

  occurred_at  timestamptz not null,
  recorded_at  timestamptz not null default now(),

  -- 'open', and room for whatever else earns a record later.
  action       text not null,
  -- O_RDONLY/O_WRONLY/... as the mount saw them, for telling a read from an
  -- edit without guessing.
  open_flags   integer,

  -- Set only when the read happened under impersonation, and never instead of
  -- principal_id. Filing an admin's impersonated reads against their subject
  -- would be laundering: the trail must always name the human who caused the
  -- read, with the identity they borrowed beside it rather than in place of it.
  acted_as     uuid references wiki.principal(id) on delete set null,

  -- The client's claim about the process. Deliberately one jsonb column rather
  -- than columns per field: the shape is the client's, it will change, and
  -- promoting any of it to a first-class column would suggest the server
  -- believes it.
  process      jsonb,

  -- Reads, and the mutations that carry a caller. Not one per FUSE operation:
  -- write() gets a file handle and no process at all, so a 'write' here is the
  -- rename that lands an editor's temp file on a real path, which is where the
  -- bytes actually become a draft. An in-place save carries no rename and
  -- shows up as an 'open' whose open_flags say O_WRONLY|O_TRUNC.
  constraint access_event_action_known
    check (action in ('open', 'create', 'write', 'delete', 'move')),
  -- A record that predates the wiki, or arrives from the future, is a broken
  -- client clock rather than a fact. Keep it, but keep it recognisable.
  constraint access_event_when check (occurred_at > '2020-01-01'::timestamptz)
);

create index access_event_principal_idx on wiki.access_event (principal_id, occurred_at desc);

create index access_event_document_idx  on wiki.access_event (document_id, occurred_at desc)
  where document_id is not null;

comment on table wiki.access_event is
  'Client-reported document opens. The principal, document and time are the '
  'server''s; everything in `process` is the client''s claim about itself.';

alter table wiki.access_event enable row level security;
